formatters:
  console:
    format: '%(levelname)s: %(message)s'
  file:
    format: "%(asctime)s - %(levelname)s:\t%(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: console
    level: INFO
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    encoding: utf-8
    filename: debug_log.txt
    formatter: file
    level: DEBUG
    mode: w
loggers:
  JPEGCompressor:
    handlers:
    - console
    - file
    level: DEBUG
    propagate: false
root:
  handlers:
  - console
  level: INFO
version: 1
